language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

install:
  - pip install -e .[i18n,testing]
  - pybabel compile --domain=pycerberus --directory=pycerberus/locales

script:
  - nosetests
