name: run tests

on:
  push:
    branches:
    - main
    - ci
  pull_request:
    branches:
    - main


jobs:
  tests-cpython:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7.18", 3.6, 3.7, 3.8, 3.9, "3.10", "3.11", "3.12", "3.13"]
    container:
      image: python:${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies and run tests
      run: |
        set -eu
        if [ "${{ matrix.python-version }}" = "2.7.18" ]; then
          pip install -U pip setuptools virtualenv
          virtualenv venv-test
        else
          python3 -m venv venv-test
        fi
        . venv-test/bin/activate
        pip install -e .[testing]
        pybabel compile --domain=pycerberus --directory=pycerberus/locales
        pytest


  tests_pypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pypy-version: ["3.10", "3.11", "latest"]
    container:
        image: pypy:${{ matrix.pypy-version }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies and run tests
      run: |
        python3 -m venv venv-test
        . venv-test/bin/activate
        pip install -e .[i18n,testing]
        pybabel compile --domain=pycerberus --directory=pycerberus/locales
        pytest
